<?php
/** Actual Control Desk renderer handoffs; no WordPress writes. */
$root=dirname(__DIR__);
function handoff_extract($source,$name){preg_match('/function '.preg_quote($name,'/').'\s*\(/',$source,$m,PREG_OFFSET_CAPTURE);if(!$m)throw new RuntimeException($name);$out='';$depth=0;$opened=false;foreach(token_get_all('<?php '.substr($source,$m[0][1])) as $t){if(is_array($t)){if(in_array($t[0],[T_CURLY_OPEN,T_DOLLAR_OPEN_CURLY_BRACES],true))$depth++;if($t[0]!==T_OPEN_TAG||$out!=='')$out.=$t[1];continue;}$out.=$t;if($t==='{'){$depth++;$opened=true;}if($t==='}'&&--$depth===0&&$opened)return $out;}throw new RuntimeException('Unclosed function');}
function __($s,$domain=''){return $s;}function esc_html($s){return htmlspecialchars((string)$s,ENT_QUOTES);}function esc_attr($s){return esc_html($s);}function esc_url($s){return esc_html($s);}function esc_html_e($s,$domain=''){echo esc_html($s);}function sanitize_key($s){return preg_replace('/[^a-z0-9_-]/','',strtolower($s));}function admin_url($s){return 'https://example.test/sub/wp-admin/'.$s;}function home_url($s){return 'https://example.test/sub'.$s;}function current_user_can($s){return true;}
function add_query_arg($args,$value=null,$url=null){if(!is_array($args))$args=[$args=>$value];else $url=$value;return $url.(str_contains($url,'?')?'&':'?').http_build_query($args);}
function lunara_site_studio_surfaces(){return array_fill_keys(['site-footer','journal-single','lunara-method'],[]);}function lunara_site_studio_journal_single_preview_article(){return ['route'=>'/journal/existing-published-article/'];}
$source=file_get_contents(getenv('LUNARA_HANDOFF_SOURCE')?:$root.'/inc/control-desk.php');
eval(handoff_extract(file_get_contents($root.'/inc/site-studio-registry.php'),'lunara_site_studio_admin_url'));
foreach(['lunara_control_desk_customizer_url','lunara_control_desk_theme_studio_groups','lunara_control_desk_theme_studio_mobile_checks','lunara_control_desk_render_theme_studio_mobile_checks','lunara_control_desk_theme_studio_goal_guides','lunara_control_desk_render_theme_studio_goal_guide','lunara_control_desk_render_useful_controls'] as $name)eval(handoff_extract($source,$name));
$checks=0;function handoff_check($ok,$message){global $checks;$checks++;if(!$ok)throw new RuntimeException($message);}function capture_handoff($fn){ob_start();$fn();return ob_get_clean();}
$footer=lunara_site_studio_admin_url('site-footer');$journal=lunara_site_studio_admin_url('journal-single');
foreach(lunara_control_desk_theme_studio_groups() as $group)if($group['label']==='Footer'){handoff_check(lunara_control_desk_customizer_url($group['section'])===$footer,'Footer group resolves shared editor');handoff_check(!in_array('lunara_footer_show_social',$group['settings'],true),'Footer guidance excludes unowned social toggle');}
$mobile=capture_handoff('lunara_control_desk_render_theme_studio_mobile_checks');handoff_check(str_contains($mobile,esc_url($footer)),'Actual mobile checks emit shared Footer URL');
$useful=capture_handoff('lunara_control_desk_render_useful_controls');handoff_check(str_contains($useful,'href="'.esc_url($footer).'">Site Studio: Footer</a>'),'Useful Footer label and URL agree');handoff_check(!str_contains($useful,'Customizer: Footer'),'Retired Footer label absent');
$classic=lunara_control_desk_customizer_url('lunara_standard_post_options');handoff_check(str_contains($classic,'customize.php'),'Mixed Journal Defaults remain Classic');handoff_check(str_contains($useful,'href="'.esc_url($classic).'">Customizer: Journal Defaults</a>'),'Useful Journal Defaults link preserved');
$guides=capture_handoff('lunara_control_desk_render_theme_studio_goal_guide');handoff_check(str_contains($guides,'href="'.esc_url($journal).'">Open Journal article presentation</a>'),'Actual goal renderer emits Journal presentation URL and label');handoff_check(str_contains($guides,'/journal/existing-published-article/'),'Guide preview targets a published article');
foreach(lunara_control_desk_theme_studio_goal_guides() as $g)if($g['goal']==='Make Journal easier to read'){handoff_check($g['touch']===['Headline size','Image fit and focal point','Author, publication date, and reading time'],'Guide touch fields match presentation owner');handoff_check(!str_contains($g['watch'],'archive'),'Guide watch fields concern article presentation');}
handoff_check(str_contains(lunara_control_desk_customizer_url('lunara_mobile_menu_options'),'autofocus%5Bsection%5D=lunara_mobile_menu_options'),'Unrelated section routing preserved');
echo "Control Desk editor handoffs: $checks checks passed.\n";
