$ErrorActionPreference = 'Stop'
$themeRoot = Split-Path -Parent $PSScriptRoot
function Assert-True([bool]$Condition,[string]$Message){if(-not $Condition){throw $Message}}
function Read-Theme([string]$Relative){$path=Join-Path $themeRoot $Relative;Assert-True (Test-Path -LiteralPath $path) "Missing expected file: $Relative";Get-Content -LiteralPath $path -Raw}
function Resolve-Home { foreach($candidate in @($env:USERPROFILE,$env:HOME,[Environment]::GetFolderPath([Environment+SpecialFolder]::UserProfile))){if(-not [string]::IsNullOrWhiteSpace("$candidate")){return "$candidate"}} throw 'Unable to resolve browser home.' }
$browserHome=Resolve-Home;$runningOnWindows=[Runtime.InteropServices.RuntimeInformation]::IsOSPlatform([Runtime.InteropServices.OSPlatform]::Windows)
function Resolve-Node { $root=Join-Path (Join-Path (Join-Path (Join-Path (Join-Path $browserHome '.cache') 'codex-runtimes') 'codex-primary-runtime') 'dependencies') 'node';$bundled=Join-Path (Join-Path $root 'bin') $(if($runningOnWindows){'node.exe'}else{'node'});if(Test-Path -LiteralPath $bundled){return $bundled};$command=Get-Command node -ErrorAction SilentlyContinue;if($command){return $command.Source};return $null }
function Resolve-Modules([string]$Node){$runtime=Join-Path (Join-Path (Join-Path (Join-Path (Join-Path (Join-Path $browserHome '.cache') 'codex-runtimes') 'codex-primary-runtime') 'dependencies') 'node') 'node_modules';$candidates=@($runtime,(Join-Path $themeRoot 'node_modules'));if($env:NODE_PATH){$candidates+=($env:NODE_PATH -split [IO.Path]::PathSeparator)};if($Node){$candidates+=[IO.Path]::GetFullPath((Join-Path (Split-Path -Parent $Node) '../node_modules'))};return $candidates|Where-Object{$_ -and ((Test-Path -LiteralPath (Join-Path $_ 'playwright-core')) -or (Test-Path -LiteralPath (Join-Path $_ 'playwright')))}|Select-Object -Unique|Select-Object -First 1}
function Resolve-Browser { $candidates=@($env:LUNARA_BROWSER_EXECUTABLE);if($env:PLAYWRIGHT_BROWSERS_PATH){$candidates+=$env:PLAYWRIGHT_BROWSERS_PATH};if($runningOnWindows){if($env:LOCALAPPDATA){$cache=Join-Path $env:LOCALAPPDATA 'ms-playwright';if(Test-Path -LiteralPath $cache){$candidates+=Get-ChildItem -LiteralPath $cache -Directory -Filter 'chromium-*' -ErrorAction SilentlyContinue|Sort-Object Name -Descending|ForEach-Object{Join-Path (Join-Path $_.FullName 'chrome-win64') 'chrome.exe'}};if($env:ProgramFiles){$candidates+=Join-Path $env:ProgramFiles 'Google\Chrome\Application\chrome.exe'};$candidates+=Join-Path $env:LOCALAPPDATA 'Google\Chrome\Application\chrome.exe'}}else{$candidates+=@('/usr/bin/google-chrome','/usr/bin/google-chrome-stable','/usr/bin/chromium','/usr/bin/chromium-browser')};return $candidates|Where-Object{$_ -and (Test-Path -LiteralPath $_)}|Select-Object -First 1}

$loader=Read-Theme 'functions-loader.php';$preview=Read-Theme 'inc/site-studio-preview.php';$studio=Read-Theme 'inc/site-studio.php';$homeBlocks=Read-Theme 'inc/home-blocks.php';$hero=Read-Theme 'functions.php';$pluginHero=Read-Theme 'inc/cinematic-home.php';$sections=Read-Theme 'inc/home-sections.php';$child=Read-Theme 'assets/js/lunara-site-studio-preview.js';$parent=Read-Theme 'assets/js/lunara-site-studio.js'
Assert-True ($loader -match '(?s)site-studio-registry\.php.*site-studio-adapters\.php.*site-studio-rest\.php.*site-studio-preview\.php.*is_admin.*site-studio\.php') 'The public preview module must load after foundation/REST and before the admin-only workspace.'
Assert-True ($preview -match "function\s+lunara_site_studio_preview_instance_query_arg" -and $preview -match "return\s+'lunara_site_studio_instance'" -and $preview -match "add_action\(\s*'template_redirect'\s*,\s*'lunara_site_studio_handle_private_preview'\s*,\s*0\s*\)") 'The preview module must own the canonical helper and priority-zero template guard.'
$callbackNames=@('lunara_handle_festival_qr_redirect','lunara_journal_archive_studio_guard_preview_request','lunara_reviews_archive_studio_guard_preview_request','lunara_oscars_portal_studio_guard_preview_request','lunara_send_home_cinematic_hero_preload_header','lunara_search_command_template_redirect');$callbackCursor=-1;foreach($callbackName in $callbackNames){$next=$preview.IndexOf("'$callbackName'",($callbackCursor+1));Assert-True ($next -gt $callbackCursor) "Missing or reordered deferred priority-zero callback: $callbackName";$callbackCursor=$next}
Assert-True ($preview -match '(?s)remove_action\(\s*''template_redirect''\s*,\s*\$callback\s*,\s*0\s*\).*?\$deferred[^;]*\[\]' -and $preview -match '(?s)add_action\(\s*''template_redirect''\s*,\s*''lunara_site_studio_handle_private_preview''\s*,\s*0\s*\).*?foreach\s*\(\s*\$deferred.*?add_action\(\s*''template_redirect''\s*,\s*\$callback\s*,\s*0\s*\)') 'The module must record only successfully removed exact-priority callbacks, add Site Studio first, then restore only that recorded list.'
Assert-True ($preview -match 'lunara_site_studio_prepare_private_preview_response' -and $preview -match 'lunara_site_studio_get_private_preview' -and $preview -match 'is_front_page') 'The guard must prepare private response headers and consume the existing owner-bound store only on front page.'
Assert-True ($preview -notmatch '(?i)\b(?:set_(?:site_)?transient|delete_(?:site_)?transient|add_(?:site_|network_)?option|update_(?:site_|network_)?option|delete_(?:site_|network_)?option|set_theme_mod|remove_theme_mod|wp_(?:insert|update|delete|trash|untrash)_post|add_post_meta|update_post_meta|delete_post_meta|add_metadata|update_metadata|delete_metadata|update_user_meta|delete_user_meta|wp_cache_(?:add|set|replace|delete|flush|flush_group|flush_runtime|incr|decr)|clean_[a-z0-9_]*_cache|flush_rewrite_rules|flush_cache|purge_cache|invalidate_cache|wp_(?:insert|update|delete)_term)\s*\(' -and $preview -notmatch '(?i)\$wpdb\s*->\s*(?:insert|update|delete|replace|query)\s*\(' -and $preview -notmatch '(?i)do_action\s*\(\s*[''"][^''"]*(?:cache|invalidate|purge|flush|clean)[^''"]*[''"]') 'The public preview module must contain no direct DB/option/mod/transient/post/meta/term/cache write, purge, cleanup, query, rewrite, or invalidation primitive.'
$shapeStart=$preview.IndexOf('function lunara_site_studio_preview_key_shape');$shapeEnd=$preview.IndexOf("if ( ! function_exists(",($shapeStart+10));$shapeBody=if($shapeStart -ge 0 -and $shapeEnd -gt $shapeStart){$preview.Substring($shapeStart,$shapeEnd-$shapeStart)}else{''}
Assert-True ($shapeBody -and $shapeBody -notmatch 'sanitize_key\s*\(|apply_filters\s*\(') 'Pre-header preview-shape detection must use only local byte/string normalization and no filterable sanitizer or extension callback.'
$resolveStart=$preview.IndexOf('function lunara_site_studio_resolve_private_preview');$resolveEnd=$preview.IndexOf("if ( ! function_exists(",($resolveStart+10));$resolveBody=if($resolveStart -ge 0 -and $resolveEnd -gt $resolveStart){$preview.Substring($resolveStart,$resolveEnd-$resolveStart)}else{''}
$methodOrder=$resolveBody.IndexOf('REQUEST_METHOD');$originOrder=$resolveBody.IndexOf('preview_request_origin');$queryOrder=$resolveBody.IndexOf('preview_exact_query');$registryOrder=$resolveBody.IndexOf('lunara_site_studio_get_surface');$routeOrder=$resolveBody.IndexOf('preview_request_path')
Assert-True ($methodOrder -ge 0 -and $originOrder -gt $methodOrder -and $queryOrder -gt $originOrder -and $registryOrder -gt $queryOrder -and $routeOrder -gt $registryOrder) 'Resolver must enforce exact method/origin, then raw query, then registry, then exact deployed path/front-page authorization in the locked order.'
$seamCalls=[regex]::Matches($homeBlocks,'lunara_home_front_page_content\(\s*\$page_id\s*\)').Count
$writeStart=$homeBlocks.IndexOf('function lunara_write_home_section_blocks');$writeEnd=$homeBlocks.IndexOf("if ( ! function_exists(",($writeStart+10));$writeBody=if($writeStart -ge 0 -and $writeEnd -gt $writeStart){$homeBlocks.Substring($writeStart,$writeEnd-$writeStart)}else{''}
Assert-True ($homeBlocks -match 'function\s+lunara_home_front_page_content\s*\(' -and $homeBlocks -match 'apply_filters\(\s*[''"]lunara_home_front_page_content[''"]' -and $seamCalls -eq 3 -and ([regex]::Matches($writeBody,"get_post_field\(\s*'post_content'")).Count -eq 2 -and $writeBody -notmatch 'lunara_home_front_page_content') 'The Home seam must be its declaration plus exactly two public reads, while transaction/write readback retains exactly two raw canonical post reads.'
foreach($publicReader in @('lunara_home_uses_block_composition','lunara_render_home_block_composition')){$readerStart=$homeBlocks.IndexOf("function $publicReader");$readerEnd=$homeBlocks.IndexOf("if ( ! function_exists(",($readerStart+10));$readerBody=if($readerStart -ge 0 -and $readerEnd -gt $readerStart){$homeBlocks.Substring($readerStart,$readerEnd-$readerStart)}else{''};Assert-True ($readerBody -and ([regex]::Matches($readerBody,'lunara_home_front_page_content\(\s*\$page_id\s*\)')).Count -eq 1 -and $readerBody -notmatch "get_post_field\(\s*'post_content'") "$publicReader must own exactly one preview seam read and no direct canonical post read."}
$marker='data-lunara-site-studio-section';$allMarkerText=$hero+"`n"+$pluginHero+"`n"+$sections;foreach($slug in @('hero','latest-reviews','pairing-desk','dispatch','oscar-picks','oscar-facts')){Assert-True ($allMarkerText -match ($marker+'=["'']'+[regex]::Escape($slug)+'["'']')) "Missing canonical public marker: $slug"}
Assert-True (([regex]::Matches($allMarkerText,$marker+'=["'']hero["'']')).Count -eq 2) 'Hero must have exactly plugin-backed and common-tail ownership sites.'
Assert-True (([regex]::Matches($allMarkerText,$marker+'=["''][^"'']+["'']')).Count -eq 7 -and ([regex]::Matches($pluginHero,$marker)).Count -eq 1 -and ([regex]::Matches($sections,$marker)).Count -eq 1 -and ([regex]::Matches($hero,$marker)).Count -eq 5) 'The three production owners must contain exactly the seven approved marker sites and no extras.'
$deadLatestStart=$hero.IndexOf('function lunara_render_homepage_latest_reviews');$deadLatest=if($deadLatestStart -ge 0){$hero.Substring($deadLatestStart)}else{''}
Assert-True ($deadLatestStart -ge 0 -and $deadLatest -notmatch $marker -and ([regex]::Matches($sections,'function\s+lunara_render_homepage_latest_reviews')).Count -eq 1 -and ([regex]::Matches($sections,$marker+'=["'']latest-reviews["'']')).Count -eq 1) 'Latest Reviews marker must live only in the active provider and never in the guarded dead fallback.'
Assert-True ($pluginHero -match '(?s)function\s+lunara_render_plugin_backed_home_hero\b.*?<section\s+class="lunara-home-cinematic-front-door lunara-home-plugin-hero is-plugin-backed"\s+data-lunara-site-studio-section="hero"' -and $sections -match '(?s)function\s+lunara_render_homepage_latest_reviews\b.*?<section\s+class="lunara-home-section lunara-home-slot-latest-reviews lunara-latest-reviews-section"\s+data-lunara-site-studio-section="latest-reviews"') 'Plugin Hero and active Latest markers must remain on their recognizable root section elements.'
Assert-True ($hero -match '(?s)function\s+lunara_render_home_pairing_desk\b.*?<section\s+id="pairing-desk"\s+class="[^"]*lunara-pairing-desk-section[^"]*"\s+data-lunara-site-studio-section="pairing-desk"' -and $hero -match '(?s)function\s+lunara_render_homepage_journal_lane\b.*?<section\s+class="lunara-home-section lunara-home-slot-dispatch lunara-dispatches-section"\s+data-lunara-site-studio-section="dispatch"' -and $hero -match '(?s)function\s+lunara_render_oscar_picks_carousel\b.*?<section\s+class="[^"]*lunara-oscar-picks-section[^"]*"\s+data-lunara-site-studio-section="oscar-picks"' -and $hero -match '(?s)function\s+lunara_render_oscar_facts_carousel\b.*?<section\s+class="lunara-home-section lunara-home-slot-oscar-facts lunara-oscar-facts-section"\s+data-lunara-site-studio-section="oscar-facts"') 'Pairing, Dispatch, Oscar Picks, and Oscar Facts markers must remain on each named renderer root.'
Assert-True ($hero -match '(?s)\$hero_html\s*=\s*function_exists.*?else\s*\{.*?\$hero_html\s*=\s*\(string\)\s*ob_get_clean\(\).*?preg_replace.*?return\s+is_string\(\s*\$hero_html') 'Both real Hero branches must converge on the single common marker-stamping tail exercised by the PHP runtime.'
Assert-True ($studio -match 'static\s+\$page_uuid.*wp_generate_uuid4\(' -and $studio -match "'pageUuid'\s*=>\s*\`$page_uuid" -and $studio -match "'previewInstanceArg'\s*=>\s*lunara_site_studio_preview_instance_query_arg\(") 'Parent config must localize only the request-stable server UUID and canonical instance argument.'
Assert-True ($child -match 'LunaraSiteStudioPreviewConfig' -and $child -match 'window\.parent\.postMessage' -and $child -match 'window\.location\.origin' -and $child -notmatch 'fetch\s*\(|XMLHttpRequest|localStorage|sessionStorage|postMessage\([^,]+,\s*[''"]\*[''"]') 'The child bridge must be local-only and derive its exact target origin from its own location.'
Assert-True ($parent -match 'addEventListener\(\s*[''"]message[''"]' -and $parent -match 'contentWindow' -and $parent -match 'previewInstanceArg') 'The parent must bind strict message validation to the active iframe generation.'

$node=Resolve-Node;$modules=Resolve-Modules $node;$browser=Resolve-Browser;Assert-True ([bool]$node) 'Node is required.';Assert-True ([bool]$modules) 'Pinned Playwright is required.';Assert-True ([bool]$browser) 'Chrome/Chromium is required.'
$priorNode=$env:NODE_PATH;$priorBrowser=$env:LUNARA_BROWSER_EXECUTABLE
try{$env:NODE_PATH=(@($modules,$priorNode)|Where-Object{$_}|Select-Object -Unique)-join[IO.Path]::PathSeparator;$env:LUNARA_BROWSER_EXECUTABLE=$browser;$php=& php (Join-Path $PSScriptRoot 'site-studio-private-preview-runtime.php') 2>&1;Assert-True ($LASTEXITCODE -eq 0) ("Private preview PHP runtime failed: "+($php-join[Environment]::NewLine));$browserOutput=& $node (Join-Path $PSScriptRoot 'site-studio-preview-bridge-runtime.js') 2>&1;Assert-True ($LASTEXITCODE -eq 0) ("Child bridge runtime failed: "+($browserOutput-join[Environment]::NewLine))}finally{$env:NODE_PATH=$priorNode;$env:LUNARA_BROWSER_EXECUTABLE=$priorBrowser}
Write-Host 'site-studio-private-preview: all assertions passed.'
